import { useEffect, useMemo, useState } from "react";
import { User } from "@supabase/supabase-js";
import {
  Check,
  Copy,
  Download,
  Eye,
  EyeOff,
  ExternalLink,
  KeyRound,
  Link2,
  Play,
  RefreshCcw,
  ShieldAlert,
  Trash2,
} from "lucide-react";
import { toast } from "@/components/ui/use-toast";
import { pricingPlansByCode, type PlanCode } from "@/data/pricingPlans";
import type { CurrentPlanSnapshot } from "@/lib/supabaseBilling";
import {
  createUserApiKey,
  fetchUserApiKeys,
  revokeUserApiKey,
  type UserApiKeyRow,
} from "@/lib/apiAccessClient";
import {
  fetchInvoiceTemplates,
  type SupabaseInvoiceTemplateRow,
} from "@/lib/supabaseTemplates";

interface ApiAccessPanelProps {
  user: User | null;
  currentPlan: CurrentPlanSnapshot;
}

const DEFAULT_TEST_BODY = `{
  "template_id": "02e0bb94-db17-44aa-b200-475402e0b552",
  "invoice_number": "INV-2024-0001",
  "variable_data": {
    "primary_color": "#6366f1",
    "accent1": "#6366f1",
    "accent2": "#8b5cf6",
    "logo_initial": "ACb",
    "company_name": "Apex Consulting",
    "company_tagline": "Strategy & Growth",
    "invoice_status": "Draft",
    "issue_date": "March 1, 2024",
    "due_date": "March 15, 2024",
    "payment_terms": "Net 14",
    "from_name": "Apex Consulting LLC",
    "from_address": "123 Business Ave, NY",
    "from_email": "billing@apex.com",
    "to_name": "NextWave Corp",
    "to_address": "500 Market Street, CA",
    "to_email": "finance@nextwave.com",
    "payment_note": "Thank you for your business.",
    "company_website": "www.apexconsulting.com",
    "footer_message": "Generated by Apex Invoice Engine",
    "line_items": [
      {
        "description": "Strategy Workshop",
        "quantity": 16,
        "unit_price": 450
      }
    ],
    "vat_rate": 8.875,
    "expenses_amount": 500
  }
}`;

const LOCAL_KEY_CACHE_PREFIX = "invoicehub_api_key_cache_v1";

function cacheKeyById(id: string): string {
  return `id:${id}`;
}

function cacheKeyByPrefix(prefix: string): string {
  return `prefix:${prefix}`;
}

function readStoredKeyCache(userId: string): Record<string, string> {
  if (typeof window === "undefined") {
    return {};
  }

  try {
    const raw = window.localStorage.getItem(`${LOCAL_KEY_CACHE_PREFIX}:${userId}`);
    if (!raw) {
      return {};
    }

    const parsed = JSON.parse(raw);
    return typeof parsed === "object" && parsed !== null && !Array.isArray(parsed)
      ? (parsed as Record<string, string>)
      : {};
  } catch {
    return {};
  }
}

function writeStoredKeyCache(userId: string, cache: Record<string, string>) {
  if (typeof window === "undefined") {
    return;
  }

  try {
    window.localStorage.setItem(`${LOCAL_KEY_CACHE_PREFIX}:${userId}`, JSON.stringify(cache));
  } catch {
    // Ignore storage failures and keep the app usable.
  }
}

function resolveStoredSecret(cache: Record<string, string>, key: Pick<UserApiKeyRow, "id" | "key_prefix">): string {
  return cache[cacheKeyById(key.id)] || cache[cacheKeyByPrefix(key.key_prefix)] || "";
}

function formatDate(value: string | null): string {
  if (!value) {
    return "Never used";
  }

  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) {
    return "Unknown";
  }

  return new Intl.DateTimeFormat("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
  }).format(parsed);
}

function parseSampleBody(template: SupabaseInvoiceTemplateRow): Record<string, unknown> | null {
  const raw = template.sample_body;
  if (!raw) {
    return null;
  }

  if (typeof raw === "string") {
    try {
      const parsed = JSON.parse(raw);
      return typeof parsed === "object" && parsed !== null && !Array.isArray(parsed)
        ? (parsed as Record<string, unknown>)
        : null;
    } catch {
      return null;
    }
  }

  return typeof raw === "object" && raw !== null && !Array.isArray(raw)
    ? (raw as Record<string, unknown>)
    : null;
}

function buildTemplateTestBody(template: SupabaseInvoiceTemplateRow): string {
  const sampleBody = parseSampleBody(template);
  const variableData =
    sampleBody?.variable_data &&
    typeof sampleBody.variable_data === "object" &&
    sampleBody.variable_data !== null &&
    !Array.isArray(sampleBody.variable_data)
      ? (sampleBody.variable_data as Record<string, unknown>)
      : sampleBody ?? {};

  const invoiceNumber =
    typeof variableData.invoice_number === "string" && variableData.invoice_number.trim() !== ""
      ? variableData.invoice_number
      : "INV-2026-1001";

  return JSON.stringify(
    {
      template_id: template.id,
      invoice_number: invoiceNumber,
      variable_data: variableData,
    },
    null,
    2
  );
}

function extractFilename(headers: Headers): string {
  const contentDisposition = headers.get("content-disposition") || "";
  const match = contentDisposition.match(/filename="?([^"]+)"?/i);
  return match?.[1] || "invoice.pdf";
}

const ApiAccessPanel = ({ user, currentPlan }: ApiAccessPanelProps) => {
  const [keys, setKeys] = useState<UserApiKeyRow[]>([]);
  const [templates, setTemplates] = useState<SupabaseInvoiceTemplateRow[]>([]);
  const [selectedTemplateId, setSelectedTemplateId] = useState("");
  const [busy, setBusy] = useState(false);
  const [newKey, setNewKey] = useState("");
  const [copied, setCopied] = useState<"" | "url" | "key">("");
  const [testerApiKey, setTesterApiKey] = useState("");
  const [testBody, setTestBody] = useState(DEFAULT_TEST_BODY);
  const [testBusy, setTestBusy] = useState(false);
  const [testStatus, setTestStatus] = useState("");
  const [testResponse, setTestResponse] = useState("");
  const [pdfUrl, setPdfUrl] = useState("");
  const [pdfFileName, setPdfFileName] = useState("invoice.pdf");
  const [storedSecrets, setStoredSecrets] = useState<Record<string, string>>({});
  const [visibleSecrets, setVisibleSecrets] = useState<Record<string, boolean>>({});

  const endpointUrl = useMemo(() => {
    const supabaseUrl = import.meta.env.VITE_SUPABASE_URL as string | undefined;
    return supabaseUrl ? `${supabaseUrl}/functions/v1/generate-pdf-api` : "";
  }, []);

  const planMeta = pricingPlansByCode[currentPlan.code as PlanCode];
  const hasApiAccess =
    currentPlan.code === "free" ||
    currentPlan.code === "pro" ||
    currentPlan.code === "business" ||
    currentPlan.code === "enterprise";

  const loadKeys = async () => {
    if (!user || !hasApiAccess) {
      setKeys([]);
      return;
    }

    try {
      setKeys(await fetchUserApiKeys());
    } catch (error: unknown) {
      toast({
        title: "API keys unavailable",
        description: error instanceof Error ? error.message : "Could not load API keys.",
        variant: "destructive",
      });
    }
  };

  const loadTemplates = async () => {
    try {
      const rows = await fetchInvoiceTemplates();
      setTemplates(rows);
      if (rows.length > 0 && !selectedTemplateId) {
        setSelectedTemplateId(rows[0].id);
      }
    } catch {
      // Leave tester usable with manual JSON even if template loading fails.
    }
  };

  useEffect(() => {
    void loadKeys();
  }, [user?.id, hasApiAccess]);

  useEffect(() => {
    if (user) {
      void loadTemplates();
    }
  }, [user?.id]);

  useEffect(() => {
    if (!user) {
      setStoredSecrets({});
      setVisibleSecrets({});
      return;
    }

    setStoredSecrets(readStoredKeyCache(user.id));
  }, [user?.id]);

  useEffect(() => {
    return () => {
      if (pdfUrl) {
        URL.revokeObjectURL(pdfUrl);
      }
    };
  }, [pdfUrl]);

  const copyValue = async (value: string, type: "" | "url" | "key") => {
    try {
      await navigator.clipboard.writeText(value);
      setCopied(type);
      window.setTimeout(() => setCopied(""), 1800);
    } catch {
      toast({
        title: "Copy failed",
        description: "Clipboard access was blocked in this browser.",
        variant: "destructive",
      });
    }
  };

  const persistSecret = (keyId: string, keyPrefix: string, secret: string) => {
    if (!user) {
      return;
    }

    setStoredSecrets((current) => {
      const next = {
        ...current,
        [cacheKeyById(keyId)]: secret,
        [cacheKeyByPrefix(keyPrefix)]: secret,
      };
      writeStoredKeyCache(user.id, next);
      return next;
    });
    setVisibleSecrets((current) => ({ ...current, [keyId]: true }));
  };

  const removeStoredSecret = (keyId: string, keyPrefix?: string) => {
    if (!user) {
      return;
    }

    setStoredSecrets((current) => {
      const next = { ...current };
      delete next[cacheKeyById(keyId)];
      if (keyPrefix) {
        delete next[cacheKeyByPrefix(keyPrefix)];
      }
      writeStoredKeyCache(user.id, next);
      return next;
    });
    setVisibleSecrets((current) => {
      const next = { ...current };
      delete next[keyId];
      return next;
    });
  };

  const handleCreateKey = async () => {
    setBusy(true);
    try {
      const created = await createUserApiKey(`Key ${keys.length + 1}`);
      setNewKey(created.api_key);
      setTesterApiKey(created.api_key);
      persistSecret(created.id, created.key_prefix, created.api_key);
      await loadKeys();
      toast({
        title: "API key created",
        description: "This secret is loaded into the tester and saved in this browser so you can view it again here.",
      });
    } catch (error: unknown) {
      toast({
        title: "Could not create API key",
        description: error instanceof Error ? error.message : "Unknown API key creation error.",
        variant: "destructive",
      });
    } finally {
      setBusy(false);
    }
  };

  const handleRevoke = async (keyId: string, keyPrefix: string) => {
    setBusy(true);
    try {
      await revokeUserApiKey(keyId);
      removeStoredSecret(keyId, keyPrefix);
      setKeys((current) => current.filter((key) => key.id !== keyId));
      await loadKeys();
      toast({
        title: "API key deleted",
        description: "That key can no longer call the managed PDF endpoint.",
      });
    } catch (error: unknown) {
      toast({
        title: "Could not delete key",
        description: error instanceof Error ? error.message : "Unknown delete error.",
        variant: "destructive",
      });
    } finally {
      setBusy(false);
    }
  };

  const handleLoadTemplateBody = () => {
    const template = templates.find((item) => item.id === selectedTemplateId);
    if (!template) {
      return;
    }
    setTestBody(buildTemplateTestBody(template));
    toast({
      title: "Sample body loaded",
      description: `Loaded a valid request body for "${template.name}".`,
    });
  };

  const handleRunTest = async () => {
    if (!endpointUrl) {
      toast({
        title: "Missing endpoint",
        description: "VITE_SUPABASE_URL is not configured.",
        variant: "destructive",
      });
      return;
    }

    if (!testerApiKey.trim()) {
      toast({
        title: "Missing API key",
        description: "Generate a key or paste your existing key into the tester first.",
        variant: "destructive",
      });
      return;
    }

    if (pdfUrl) {
      URL.revokeObjectURL(pdfUrl);
      setPdfUrl("");
    }

    setTestBusy(true);
    setTestStatus("");
    setTestResponse("");

    try {
      const parsedBody = JSON.parse(testBody);
      const response = await fetch(endpointUrl, {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: `Bearer ${testerApiKey.trim()}`,
        },
        body: JSON.stringify(parsedBody),
      });

      const contentType = response.headers.get("content-type") || "";
      setTestStatus(`${response.status} ${response.statusText}`);

      if (contentType.includes("application/pdf")) {
        const blob = await response.blob();
        const fileUrl = URL.createObjectURL(blob);
        const fileName = extractFilename(response.headers);
        setPdfUrl(fileUrl);
        setPdfFileName(fileName);
        setTestResponse(
          `PDF generated successfully.\n\nFilename: ${fileName}\nSize: ${(blob.size / 1024).toFixed(1)} KB\n\nUse the buttons below to open or download the file.`
        );
      } else {
        const text = await response.text();
        setTestResponse(text);
      }

      await loadKeys();
      if (!response.ok) {
        toast({
          title: "Test request failed",
          description: `Managed API returned ${response.status}. This still follows the normal API flow.`,
          variant: "destructive",
        });
      }
    } catch (error: unknown) {
      const message =
        error instanceof SyntaxError
          ? "Request body must be valid JSON."
          : error instanceof Error
            ? error.message
            : "Unknown API test error.";
      setTestStatus("Request failed");
      setTestResponse(message);
      toast({
        title: "Could not run API test",
        description: message,
        variant: "destructive",
      });
    } finally {
      setTestBusy(false);
    }
  };

  if (!user) {
    return null;
  }

  return (
    <section className="mt-8 rounded-3xl border border-border bg-background p-6" style={{ boxShadow: "var(--shadow-md)" }}>
      <div className="flex flex-col gap-6 lg:flex-row lg:items-start lg:justify-between">
        <div className="max-w-2xl">
          <div className="inline-flex items-center gap-2 rounded-full bg-primary/10 px-3 py-1 text-xs font-semibold uppercase tracking-[0.2em] text-primary">
            <KeyRound size={13} />
            Managed API Access
          </div>
          <h3 className="mt-4 text-3xl font-bold text-foreground">Show users the right URL and their own API key</h3>
          <p className="mt-3 text-sm leading-6 text-muted-foreground">
            Do not give users the direct `generate_pdf_via_aws` function URL anymore. Use the managed gateway endpoint below so plan limits, monthly quotas, and per-second rate limits are enforced.
          </p>
        </div>

        <div className={`rounded-2xl border px-4 py-4 text-sm ${
          hasApiAccess ? "border-emerald-200 bg-emerald-50 text-emerald-950" : "border-amber-200 bg-amber-50 text-amber-950"
        }`}>
          <div className="font-semibold">{currentPlan.name}</div>
          <div className="mt-1">
            {hasApiAccess
              ? `API enabled | ${planMeta.requestsPerSecond ?? "Unlimited"} req/sec | ${
                  planMeta.invoicesPerMonth == null ? "Unlimited" : `${planMeta.invoicesPerMonth.toLocaleString()} invoices/mo`
                }`
              : "API access is not included in this plan"}
          </div>
        </div>
      </div>

      {!hasApiAccess ? (
        <div className="mt-6 rounded-2xl border border-amber-200 bg-amber-50 px-4 py-4 text-sm text-amber-950">
          <div className="flex items-start gap-3">
            <div className="mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-xl bg-amber-100 text-amber-700">
              <ShieldAlert size={16} />
            </div>
            <div>
              <div className="font-semibold">Upgrade to unlock API access.</div>
              <div className="mt-1 text-amber-900/75">
                This plan cannot generate a managed API key yet. Upgrade to unlock higher API throughput and larger monthly volume.
              </div>
            </div>
          </div>
        </div>
      ) : (
        <>
          <div className="mt-6 grid gap-4 lg:grid-cols-[1.35fr_0.65fr]">
            <div className="rounded-2xl border border-border bg-card p-4">
              <div className="flex items-center justify-between gap-3">
                <div className="text-sm font-semibold text-foreground">Endpoint URL for this plan</div>
                <button
                  type="button"
                  onClick={() => copyValue(endpointUrl, "url")}
                  className="inline-flex items-center gap-2 rounded-xl border border-border px-3 py-2 text-xs font-semibold hover:bg-secondary"
                >
                  {copied === "url" ? <Check size={13} /> : <Copy size={13} />}
                  {copied === "url" ? "Copied" : "Copy URL"}
                </button>
              </div>
              <div className="mt-3 rounded-xl bg-secondary px-4 py-3 font-mono-code text-xs text-foreground break-all">
                {endpointUrl || "Missing VITE_SUPABASE_URL"}
              </div>
              <div className="mt-3 flex items-start gap-2 text-xs text-muted-foreground">
                <Link2 size={13} className="mt-0.5 shrink-0" />
                <span>Use `Authorization: Bearer YOUR_KEY` in browsers. `x-api-key` is best reserved for server-to-server requests.</span>
              </div>
            </div>

            <div className="rounded-2xl border border-border bg-card p-4">
              <div className="text-sm font-semibold text-foreground">Controls</div>
              <div className="mt-3 space-y-3">
                <button
                  type="button"
                  onClick={handleCreateKey}
                  disabled={busy}
                  className="w-full rounded-xl bg-navy px-4 py-3 text-sm font-semibold text-white disabled:opacity-60"
                >
                  {busy ? "Working..." : "Generate API Key"}
                </button>
                <div className="rounded-xl bg-secondary px-3 py-3 text-xs text-muted-foreground">
                  Keys are hashed in the database. Keys generated here are also saved in this browser so the user can view and copy them again later.
                </div>
              </div>
            </div>
          </div>

          {newKey && (
            <div className="mt-4 rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-4 text-emerald-950">
              <div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between">
                <div>
                  <div className="font-semibold">New API key</div>
                  <div className="mt-2 rounded-xl bg-white/80 px-4 py-3 font-mono-code text-xs break-all">{newKey}</div>
                </div>
                <button
                  type="button"
                  onClick={() => copyValue(newKey, "key")}
                  className="inline-flex items-center justify-center gap-2 rounded-xl border border-emerald-300 bg-white px-4 py-3 text-sm font-semibold text-emerald-900"
                >
                  {copied === "key" ? <Check size={14} /> : <Copy size={14} />}
                  {copied === "key" ? "Copied" : "Copy Key"}
                </button>
              </div>
            </div>
          )}

          <div className="mt-6 grid gap-4 xl:grid-cols-[0.88fr_1.12fr]">
            <div className="rounded-2xl border border-border bg-card p-4">
              <div className="flex items-center justify-between gap-3">
                <div className="text-sm font-semibold text-foreground">Issued keys</div>
                <button
                  type="button"
                  onClick={() => void loadKeys()}
                  className="inline-flex items-center gap-2 rounded-xl border border-border px-3 py-2 text-xs font-semibold hover:bg-secondary"
                >
                  <RefreshCcw size={13} />
                  Refresh
                </button>
              </div>

              <div className="mt-4 space-y-3">
                {keys.length === 0 ? (
                  <div className="rounded-xl bg-secondary px-4 py-4 text-sm text-muted-foreground">
                    No API keys yet. Generate one to start using the managed PDF endpoint.
                  </div>
                ) : (
                  keys.map((key) => {
                    const storedSecret = resolveStoredSecret(storedSecrets, key);

                    return (
                    <div key={key.id} className="flex flex-col gap-3 rounded-2xl border border-border px-4 py-4">
                      <div>
                        <div className="font-semibold text-foreground">{key.label}</div>
                        {storedSecret ? (
                          <div className="mt-2 rounded-xl bg-secondary px-3 py-3">
                            <div className="flex flex-wrap items-center gap-2">
                              <div className="text-[11px] font-semibold uppercase tracking-[0.18em] text-muted-foreground">
                                Saved Key
                              </div>
                              <button
                                type="button"
                                onClick={() =>
                                  setVisibleSecrets((current) => ({
                                    ...current,
                                    [key.id]: !current[key.id],
                                  }))
                                }
                                className="inline-flex items-center gap-1 rounded-lg border border-border px-2 py-1 text-[11px] font-semibold text-foreground hover:bg-background"
                              >
                                {visibleSecrets[key.id] ? <EyeOff size={12} /> : <Eye size={12} />}
                                {visibleSecrets[key.id] ? "Hide" : "Show"}
                              </button>
                              <button
                                type="button"
                                onClick={() => void copyValue(storedSecret, "key")}
                                className="inline-flex items-center gap-1 rounded-lg border border-border px-2 py-1 text-[11px] font-semibold text-foreground hover:bg-background"
                              >
                                {copied === "key" ? <Check size={12} /> : <Copy size={12} />}
                                {copied === "key" ? "Copied" : "Copy"}
                              </button>
                            </div>
                            <div className="mt-2 font-mono-code text-xs text-foreground break-all">
                              {visibleSecrets[key.id] ? storedSecret : `${key.key_prefix}${"*".repeat(16)}`}
                            </div>
                          </div>
                        ) : (
                          <>
                            <div className="mt-1 font-mono-code text-xs text-muted-foreground">{key.key_prefix}...</div>
                            <div className="mt-2 text-xs text-muted-foreground">
                              Full key is not recoverable from the server. Generate a replacement key in this browser if you need to see the full secret again.
                            </div>
                          </>
                        )}
                        <div className="mt-2 text-xs text-muted-foreground">
                          Created: {formatDate(key.created_at)} | Last used: {formatDate(key.last_used_at)}
                        </div>
                      </div>
                      <button
                        type="button"
                        onClick={() => handleRevoke(key.id, key.key_prefix)}
                        disabled={busy}
                        className="inline-flex items-center justify-center gap-2 rounded-xl border border-border px-4 py-3 text-sm font-semibold text-foreground hover:bg-secondary disabled:opacity-60"
                      >
                        <Trash2 size={14} />
                        Delete Key
                      </button>
                    </div>
                  )})
                )}
              </div>
              {keys.length > 0 && (
                <div className="mt-4 rounded-xl bg-secondary px-4 py-3 text-xs text-muted-foreground">
                  Keys created from this browser can be viewed again here. Older keys without a saved local copy only show their prefix for security.
                </div>
              )}
            </div>

            <div className="rounded-2xl border border-border bg-card p-4">
              <div className="flex items-center justify-between gap-3">
                <div>
                  <div className="text-sm font-semibold text-foreground">API Tester</div>
                  <div className="mt-1 text-xs text-muted-foreground">
                    Uses your own API key and the managed endpoint, so the request consumes your normal plan credits.
                  </div>
                </div>
                <button
                  type="button"
                  onClick={handleRunTest}
                  disabled={testBusy}
                  className="inline-flex items-center gap-2 rounded-xl bg-navy px-4 py-3 text-sm font-semibold text-white disabled:opacity-60"
                >
                  <Play size={14} />
                  {testBusy ? "Running..." : "Run Test"}
                </button>
              </div>

              <div className="mt-4 space-y-4">
                <div className="grid gap-3 lg:grid-cols-[1fr_auto]">
                  <div>
                    <label className="mb-2 block text-xs font-semibold uppercase tracking-[0.18em] text-muted-foreground">
                      Load Sample From Template
                    </label>
                    <select
                      value={selectedTemplateId}
                      onChange={(event) => setSelectedTemplateId(event.target.value)}
                      className="w-full rounded-xl border border-border bg-background px-4 py-3 text-sm"
                    >
                      <option value="">Choose a template</option>
                      {templates.map((template) => (
                        <option key={template.id} value={template.id}>
                          {template.name}
                        </option>
                      ))}
                    </select>
                  </div>
                  <div className="flex items-end">
                    <button
                      type="button"
                      onClick={handleLoadTemplateBody}
                      disabled={!selectedTemplateId}
                      className="w-full rounded-xl border border-border px-4 py-3 text-sm font-semibold hover:bg-secondary disabled:opacity-60"
                    >
                      Load Sample
                    </button>
                  </div>
                </div>

                <div>
                  <label className="mb-2 block text-xs font-semibold uppercase tracking-[0.18em] text-muted-foreground">
                    API Key
                  </label>
                  <input
                    type="text"
                    value={testerApiKey}
                    onChange={(event) => setTesterApiKey(event.target.value)}
                    placeholder="Paste your API key here or generate a new one above"
                    className="w-full rounded-xl border border-border bg-background px-4 py-3 text-sm font-mono-code"
                  />
                </div>

                <div>
                  <label className="mb-2 block text-xs font-semibold uppercase tracking-[0.18em] text-muted-foreground">
                    Request Body
                  </label>
                  <textarea
                    value={testBody}
                    onChange={(event) => setTestBody(event.target.value)}
                    className="min-h-80 w-full rounded-xl border border-border bg-background px-4 py-3 text-xs font-mono-code"
                  />
                  <div className="mt-2 text-xs text-muted-foreground">
                    This AWS PDF function expects `template_id` and `variable_data`. Loading a sample template above gives you a valid starting body.
                  </div>
                </div>

                <div className="rounded-2xl bg-secondary p-4">
                  <div className="text-xs font-semibold uppercase tracking-[0.18em] text-muted-foreground">
                    Result
                  </div>
                  <div className="mt-2 text-sm font-semibold text-foreground">
                    {testStatus || "No request sent yet"}
                  </div>
                  <pre className="mt-3 max-h-72 overflow-auto whitespace-pre-wrap break-words rounded-xl bg-white px-4 py-3 text-xs text-foreground">
                    {testResponse || "Run the tester and the response will appear here."}
                  </pre>

                  {pdfUrl && (
                    <div className="mt-3 flex flex-wrap gap-3">
                      <a
                        href={pdfUrl}
                        target="_blank"
                        rel="noreferrer"
                        className="inline-flex items-center gap-2 rounded-xl border border-border bg-white px-4 py-3 text-sm font-semibold text-foreground"
                      >
                        <ExternalLink size={14} />
                        Open PDF
                      </a>
                      <a
                        href={pdfUrl}
                        download={pdfFileName}
                        className="inline-flex items-center gap-2 rounded-xl bg-navy px-4 py-3 text-sm font-semibold text-white"
                      >
                        <Download size={14} />
                        Download PDF
                      </a>
                    </div>
                  )}
                </div>
              </div>
            </div>
          </div>
        </>
      )}
    </section>
  );
};

export default ApiAccessPanel;
