export type PlanCode = "free" | "pro" | "business" | "enterprise";

export interface PricingPlan {
  code: PlanCode;
  name: string;
  badge: string;
  monthlyLabel: string;
  monthlyPriceMin: number | null;
  monthlyPriceMax: number | null;
  invoicesPerMonth: number | null;
  requestsPerSecond: number | null;
  popular?: boolean;
  accentClass: string;
  borderClass: string;
  ctaLabel: string;
  ctaHref: string;
  summary: string;
  audience: string;
  included: string[];
  excluded: string[];
}

export const pricingPlans: PricingPlan[] = [
  {
    code: "free",
    name: "Free Tier",
    badge: "Starter",
    monthlyLabel: "$0 / month",
    monthlyPriceMin: 0,
    monthlyPriceMax: 0,
    invoicesPerMonth: 100,
    requestsPerSecond: 1,
    accentClass: "from-emerald-500/15 via-emerald-400/5 to-transparent",
    borderClass: "border-emerald-200",
    ctaLabel: "Start Free",
    ctaHref: "/auth",
    summary: "Onboarding + virality with everything needed to try the product.",
    audience: "Best for solo users getting started.",
    included: [
      "100 invoices / month",
      "1 request / second",
      "Access to all templates",
      "Basic PDF generation",
      "API access",
      "Watermark: Generated by InvoiceHub",
    ],
    excluded: [
      "No custom branding",
      "No automation workflows",
    ],
  },
  {
    code: "pro",
    name: "Pro Tier",
    badge: "Most Popular",
    monthlyLabel: "$9 - $19 / month",
    monthlyPriceMin: 9,
    monthlyPriceMax: 19,
    invoicesPerMonth: 1000,
    requestsPerSecond: 5,
    popular: true,
    accentClass: "from-sky-500/20 via-indigo-500/10 to-transparent",
    borderClass: "border-sky-300",
    ctaLabel: "Upgrade to Pro",
    ctaHref: "https://wa.me/201554670453?text=I%20want%20to%20upgrade%20to%20the%20Pro%20plan%20for%20InvoiceHub",
    summary: "The main revenue plan with higher limits and branded output.",
    audience: "Best for freelancers and small teams shipping client invoices.",
    included: [
      "1,000 invoices / month",
      "5 requests / second",
      "Remove watermark",
      "Custom branding (logo, colors)",
      "Save invoice templates",
      "API access",
      "Priority processing",
    ],
    excluded: [
      "No team access",
    ],
  },
  {
    code: "business",
    name: "Business Tier",
    badge: "Scale",
    monthlyLabel: "$29 - $49 / month",
    monthlyPriceMin: 29,
    monthlyPriceMax: 49,
    invoicesPerMonth: 10000,
    requestsPerSecond: 10,
    accentClass: "from-fuchsia-500/20 via-violet-500/10 to-transparent",
    borderClass: "border-fuchsia-200",
    ctaLabel: "Talk About Business",
    ctaHref: "https://wa.me/201554670453?text=I%20want%20to%20upgrade%20to%20the%20Business%20plan%20for%20InvoiceHub",
    summary: "Built for apps and operations teams that need scale and integrations.",
    audience: "Good fit for SaaS apps, marketplaces, and agencies.",
    included: [
      "10,000 invoices / month",
      "10 requests / second",
      "Full API access",
      "Automation (Zapier / n8n / Bubble)",
      "Team access (3 users)",
      "Advanced templates",
      "Invoice history storage",
      "Faster rendering queue",
    ],
    excluded: [],
  },
  {
    code: "enterprise",
    name: "Enterprise Tier",
    badge: "Custom",
    monthlyLabel: "Custom pricing",
    monthlyPriceMin: null,
    monthlyPriceMax: null,
    invoicesPerMonth: null,
    requestsPerSecond: null,
    accentClass: "from-amber-500/20 via-orange-500/10 to-transparent",
    borderClass: "border-amber-200",
    ctaLabel: "Contact Sales",
    ctaHref: "https://wa.me/201554670453?text=I%20want%20Enterprise%20pricing%20for%20InvoiceHub",
    summary: "White-label, dedicated infrastructure, and high-volume generation.",
    audience: "Designed for large platforms with strict uptime and integration needs.",
    included: [
      "Unlimited invoices",
      "Unlimited requests",
      "Dedicated server / priority queue",
      "SLA (99.9% uptime)",
      "Custom integrations",
      "White-label solution",
      "Dedicated support",
      "Bulk generation (1000+ invoices instantly)",
    ],
    excluded: [],
  },
];

export const pricingPlansByCode = Object.fromEntries(
  pricingPlans.map((plan) => [plan.code, plan])
) as Record<PlanCode, PricingPlan>;
